FROM python:3.11-slim

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y gcc default-libmysqlclient-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR main/

COPY . .


# Install spacy for Microsoft presideo
RUN pip3 install -U spacy
RUN python -m spacy download en_core_web_lg

RUN pip3 install -r requirements.txt



# HEALTHCHECK CMD curl --fail http://localhost:80/_stcore/health

ENTRYPOINT ["streamlit", "run", "app.py", "--server.port", "80"]